import PolyaTopology.GeneralTopology.MetricSpaces
import PolyaTopology.GeneralTopology.TopologicalSpaces
import PolyaTopology.GeneralTopology.BasicExamples
import PolyaTopology.GeneralTopology.Closure
import PolyaTopology.GeneralTopology.Continuity
import PolyaTopology.GeneralTopology.Homeomorphisms
import PolyaTopology.GeneralTopology.Products
import PolyaTopology.GeneralTopology.Quotients
import PolyaTopology.GeneralTopology.Separation
import PolyaTopology.GeneralTopology.Connectedness
import PolyaTopology.GeneralTopology.Sequences
import PolyaTopology.GeneralTopology.Compactness

/-! @subject generaltopology
@title General Topology
@author Eric Klavins
@license CC-BY-SA-4.0
@reference Urs Schreiber, Introduction to Topology 1 — Point-set Topology, nLab: https://ncatlab.org/nlab/show/Introduction+to+Topology+--+1 — this subject follows its selection and order of results; the prose, the Lean, and the problems are written here.
@reference The nLab: https://ncatlab.org
Topology is the study of nearness without measurement: of which points lie close to which, asked without any account of how close. The subject begins one step before that, with measurement itself. A metric space is a set together with a rule assigning a distance to each pair of its points, and nearly every space a working mathematician meets carries such a rule. From the distances one reads off the balls, from the balls the open sets, and from the open sets the topology. By the end of that passage the distances have been forgotten and only the nearness remains.

**Metric Spaces** builds the beginning of it. We define a metric space, deduce from its axioms the two facts the axioms did not ask for, and construct the open balls, the closed balls and the spheres. We say what it means for a set to be bounded. We then treat the source of most metrics in practice: a norm on a real vector space, which measures the length of a vector and so the distance between two of them. The section ends on the plane, where two different norms — the one that adds the magnitudes of the coordinates and the one that takes the larger of them — have visibly different unit balls, a diamond and a square, and yet each one's balls fit inside the other's. That is the first sign that a topology remembers less than a metric does.

**Topological Spaces** makes the passage. We single out the sets a metric calls open, prove the three properties they have, and then take those three properties as a definition that needs no distance at all. Every metric space becomes a topological space; closed sets and neighbourhoods follow, and a set turns out to be open exactly when it is a neighbourhood of each of its own points — the form in which nearly every later statement is made.

**Basic Examples** stocks the subject. The two extremes that bound every topology on a set, the two-point space whose asymmetry is the source of most counterexamples, the topology whose open sets leave out only finitely many points, and the one a subset inherits from the space around it — the construction by which nearly every space one meets is built.

**Closure, Interior and Boundary** puts the apparatus to work on an arbitrary set. Every set sits inside a smallest closed set and around a largest open one; what lies between the two is its boundary, and it is empty exactly when the set is both open and closed. A point belongs to the closure exactly when the set is found arbitrarily near it, which in a metric space is a statement about balls. The section ends with the rationals, a countable set whose closure is the whole real line.

**Continuous Functions** says which maps a topology admits. We give the ε-δ definition first, for metric spaces, and then the definition that needs no distances: a map is continuous when the preimage of every open set is open. The two agree wherever both can be read, which is the theorem that licenses the abstract one. Continuity then has a closed-set form, a closure form and a pointwise form, and the section ends by testing the definition on the example spaces — where the two-point space turns out to record an open subset exactly, so that the maps into it are the open sets of the space they come from.

**Homeomorphisms** asks when two spaces are the same space. A map that is continuous, invertible, and whose inverse is continuous carries the open sets of one onto the open sets of the other, and nothing a topology can see then tells the two apart. Such a map is both an open map and a closed map, and a continuous bijection is one exactly when it is open — which a continuous bijection need not be. The section ends by putting the notion to work in both directions: the plane measured by the taxicab length and the plane measured by the supremum length are the same space, though the lengths differ at almost every pair of points, while the three topologies a two-point set carries are shown to be three different spaces.

**Subspaces and Products** makes new spaces out of old, and asks of each what maps it admits. The topology a subset inherits is the one that makes a map into the subset no harder to test than a map into the whole space around it; the same construction along any map at all gives the coarsest topology making that map continuous, and the subspace is one case of it. The product of two spaces calls a set open when every point of it has a box around it inside, the two projections out of it are continuous and — unusually — open, and a map into it is a pair of maps, continuous exactly when both of them are. The section ends where the subject began: the plane under the supremum distance is the product of two copies of the line, because a supremum ball is a square, and the taxicab plane is one too, since the last section made it the same space.

**Quotients and Sums** builds the constructions the last section's are dual to. Reverse the arrow of the induced topology: given a map out of a space, call a set open below when its preimage is open above, and the result is the finest topology that map allows. Gluing points together by an equivalence relation is that construction along the map carrying a point to its class, and laying two spaces side by side is it along the two injections at once. A map out of either is then no harder to test than a map out of what it was built from: a map out of a quotient is a map that does not distinguish related points, and a map out of a sum is a pair of maps. The section ends by collapsing a subset of a space to a single point, and showing that the point a closed subset becomes is a closed point of what is left.

**Separation Axioms** asks the first question one asks of a space: how well its open sets tell its points apart. Three conditions of increasing strength say that one of two distinct points has an open set the other misses, that each of them does, and that the two sets may be chosen disjoint — the last being the Hausdorff condition. Every metric space satisfies it, while the example spaces of the earlier sections fail the three at every level, which is what shows no two of them to be the same condition. Each has a second form written with closures: a space is T₁ exactly when its points are closed sets, T₀ exactly when the closure of a point determines the point, and Hausdorff exactly when the diagonal is closed in the square of the space. All three pass to a subspace, to a product and across a homeomorphism. Above them stand two more, separating a point from a closed set and then two closed sets from each other; a discrete space satisfies both, and every metric space is regular.

**Connectedness** asks whether a space is in one piece. A set both open and closed is a piece cut cleanly out of it, and a space with no such piece but the empty set and itself is connected; a subset is connected when no two open sets divide it, which says exactly that the space the subset inherits is connected. The codiscrete topology is connected and a two-point discrete space is not, and between the two extremes stands the theorem the subject has owed since the real line was defined: an interval does not fall apart, which is the least upper bound property in another form. A continuous map carries a connected set to a connected set, so no homeomorphism can tell a connected space from a disconnected one, and on the line that one sentence is the intermediate value theorem of calculus. What is not connected still decomposes: every point lies in a largest connected set, its component; the components are closed and partition the space, and in a discrete space they are the points themselves. The section ends with the everyday reason for believing a space to be in one piece, which is that one can walk across it — a path is a continuous map from the unit interval, and a space whose points are joined by paths is connected because the interval is.

**Sequences and Convergence** returns to the idea analysis began with, and asks how much of it a topology keeps. A sequence converges to a point when its terms end up arbitrarily near that point, which in a metric space is a statement about balls and in any space a statement about neighbourhoods; wherever both readings can be had they agree. Uniqueness of the limit is no part of the idea but a demand on the space: in a codiscrete space every point is a limit of every sequence, in a Hausdorff space there is at most one, and a space with unique limits is at least T₁. Sequences then re-describe what the earlier sections built — a point of the closure of a set is the limit of a sequence in the set, a set is closed exactly when it holds the limits of its own convergent sequences, and a map between metric spaces is continuous exactly when it preserves limits. The section ends where analysis proper begins: a sequence whose terms bunch together need not have anything to bunch up at, and a space in which it always does is complete.

**Compactness** asks a question about covers. Spread open sets over a space until they cover it and infinitely many may be needed; a set is compact when finitely many always suffice. Finitely many points are compact whatever topology they carry, a codiscrete space is compact however large, and a discrete space with infinitely many points is the first space here that is not. Compactness passes to the closed subsets of a compact space and forward along every continuous map, so no homeomorphism can see past it. In a metric space a compact set is held by a single ball and holds every point it approaches, which on the line makes it a set with a largest and a smallest element — and that is the extreme value theorem of calculus, stated for any space at all. The section ends on the theorem the whole of it was built for: the unit interval is compact, proved from the least upper bound property by pushing a finite subcover rightwards as far as it will go, which turns out to be all the way.

Mathlib's own metric spaces and topological spaces are not imported, and no problem may appeal to them. Everything is built from the real numbers, sets, and the language of real vector spaces, so that a student who finishes has the apparatus rather than a borrowed name for it. One consequence is visible in the choice of examples: the Euclidean length of a vector in the plane requires a square root, which is beyond what this fence holds, so the plane is measured here by two lengths that need no roots at all.
-/
